apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roi-dtc-march-u305/internal-image@sha256:9c1a4852f767f56d929d463006fa91876a7cff205771297570defb5cfdb481ae
        env: 
        - name: PORT
          value: "8082"
        - name: GOOGLE_CLOUD_PROJECT
          value: "<PROJECT_ID>"
        ports:
        - containerPort: 8082
            
        
